//! Result caching around selected checks through moon.
//!
//! Each selected check becomes one moon task whose command is the ordinary
//! tool check for that check. moon hashes the task's inputs, skips work whose
//! inputs already passed, and can share results through a remote cache. The
//! caller owns check semantics, budgets and receipts; moon only adds result
//! reuse. The moon configuration is generated for each run and is not
//! committed to the repository; the remote cache address comes from
//! `CCID_REMOTE_CACHE`.
use crate::{event, failure, process::Runner, value, Environment, Result};
use serde::{Deserialize, Serialize};
use serde_json::json;
use sha2::{Digest, Sha256};
use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    time::{Duration, Instant},
};

const MARKER: &str = "# ccid-generated: regenerated by `ccid cached` on every run; do not edit.";
const RESULTS: &str = ".ccid/results";
/// Every tool check locks the repository's target cache, so tasks run one at a time.
const MUTEX: &str = "ccid-target";

/// Check declaration as owned by the caller's manifest. Field-for-field
/// compatible with ccid's manifest check: the tool identity hashes the whole
/// declaration, so this struct must serialize exactly like the caller's.
#[derive(Debug, Clone, Deserialize, Serialize, Default)]
#[serde(default, deny_unknown_fields)]
pub struct Check {
    pub kind: String,
    pub actions: Option<Vec<String>>,
    pub toolchain: Option<String>,
    pub workspace: bool,
    pub all_features: bool,
    pub all_targets: bool,
    pub release: bool,
    pub features: Vec<String>,
    pub packages: Vec<String>,
    pub exclude: Vec<String>,
    pub test_runner: Option<String>,
    pub mode: Option<String>,
    pub expected_checks: Option<Vec<String>>,
    pub checks: Vec<String>,
    pub manager: Option<String>,
    pub scripts: Option<Vec<String>>,
    pub install: Option<bool>,
    pub commands: Vec<Vec<String>>,
    pub cache_outputs: Vec<String>,
    pub cache_tools: Vec<Vec<String>>,
    pub cache_env: Vec<String>,
    pub cache_commit: bool,
    pub cache_inputs: Option<Vec<String>>,
}

/// Validated execution request. The caller owns manifest parsing, check
/// selection and the cached-plan event; this request carries everything moon
/// needs to reproduce the run.
pub struct Request {
    pub repo: PathBuf,
    pub project: String,
    pub manifest_arg: String,
    pub checks: BTreeMap<String, Check>,
    pub selected: Vec<String>,
    pub plan: bool,
    pub force: bool,
    /// Tool executable invoked per task (ccid) and hashed into identities.
    pub tool: String,
    /// Exact tool revision hashed into every task identity.
    pub tool_revision: String,
    pub environment: Environment,
}

/// Validate the selected checks before any execution: moon task names,
/// repository-relative inputs, explicit outputs and tool probes.
pub fn validate_selection(checks: &BTreeMap<String, Check>, selected: &[String]) -> Result<()> {
    for name in selected {
        let check = checks
            .get(name)
            .ok_or_else(|| failure(format!("Selected check {name} is not declared")))?;
        task_id(name)?;
        validate_cache_inputs(check)?;
        for output in &check.cache_outputs {
            safe_relative(Path::new(output))?;
            if output.starts_with('.') || output.contains(['*', '?', '[', ']']) {
                return Err(failure(
                    "Cached outputs must be explicit, non-hidden relative paths",
                ));
            }
        }
        for command in &check.cache_tools {
            validate_command(command)?;
        }
    }
    Ok(())
}

/// Run the selected checks through moon so unchanged inputs reuse earlier results.
pub fn execute(request: &Request) -> Result<()> {
    validate_selection(&request.checks, &request.selected)?;
    if request.plan {
        return Ok(());
    }
    let root = request.repo.canonicalize()?;
    let runner = Runner::new(
        root.clone(),
        request.environment.clone(),
        Duration::from_secs(120),
    )?;
    let moon_version = runner.run(&argv(&["moon", "--version"]), true)?;
    let mut identities = BTreeMap::new();
    let mut probes = BTreeMap::new();
    for name in &request.selected {
        let identity = tool_identity(
            &runner,
            &request.checks[name],
            &request.environment,
            &request.tool,
            &request.tool_revision,
            &mut probes,
        )?;
        identities.insert(name.clone(), identity);
    }
    event(json!({"event":"cached-identity","moon":moon_version,"identities":identities}));

    write_generated(
        &root.join(".moon/workspace.yml"),
        &render_workspace(&request.project),
    )?;
    write_generated(
        &root.join("moon.yml"),
        &render_tasks(
            &request.checks,
            &request.selected,
            &request.manifest_arg,
            &request.tool,
            &identities,
        ),
    )?;
    // Results are task outputs: a cache hit restores them, a miss writes them fresh.
    let results = root.join(RESULTS);
    if results.exists() {
        fs::remove_dir_all(&results)?;
    }

    let mut moon_environment = request.environment.clone();
    // Transport configuration must not change task hashes between schedulers.
    // moon supports configuring its cache endpoint without rewriting workspace files.
    if let Some(url) = remote_cache(&moon_environment)? {
        moon_environment.insert("MOON_REMOTE_HOST".into(), url.clone().into());
        moon_environment.insert(
            "MOON_REMOTE_API".into(),
            if url.starts_with("http") {
                "http"
            } else {
                "grpc"
            }
            .into(),
        );
        moon_environment.insert("MOON_REMOTE_CACHE_COMPRESSION".into(), "zstd".into());
    }
    let mut command = argv(&["moon", "run"]);
    command.extend(
        request
            .selected
            .iter()
            .map(|name| format!("{}:{name}", request.project)),
    );
    if request.force {
        command.push("--force".into());
    }
    let timeout = value(&moon_environment, "CI_TIMEOUT")
        .and_then(|v| v.parse::<u64>().ok())
        .unwrap_or(2700);
    let started = Instant::now();
    Runner::new(root, moon_environment, Duration::from_secs(timeout))?.run(&command, false)?;
    event(
        json!({"event":"cached-finish","checks":request.selected,"seconds":started.elapsed().as_secs_f64()}),
    );
    Ok(())
}

fn argv(args: &[&str]) -> Vec<String> {
    args.iter().map(|s| (*s).to_owned()).collect()
}

/// moon task identifiers: letters, digits, dash and underscore.
fn task_id(name: &str) -> Result<()> {
    let valid = name
        .bytes()
        .next()
        .is_some_and(|b| b.is_ascii_alphanumeric())
        && name
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_');
    if valid {
        Ok(())
    } else {
        Err(failure(format!(
            "Check name {name:?} is not usable as a cached task; use letters, digits, '-' or '_'"
        )))
    }
}

/// moon project identifiers do not allow dots; manifest slugs may contain them.
pub fn project_id(slug: &str) -> String {
    slug.replace('.', "-")
}

/// The remote cache endpoint, from the runner environment (never from the repository).
pub fn remote_cache(environment: &Environment) -> Result<Option<String>> {
    match value(environment, "CCID_REMOTE_CACHE") {
        None => Ok(None),
        Some(url)
            if ["grpc://", "grpcs://", "http://", "https://"]
                .iter()
                .any(|scheme| url.starts_with(scheme)) =>
        {
            Ok(Some(url))
        }
        Some(_) => Err(failure(
            "CCID_REMOTE_CACHE must start with grpc://, grpcs://, http:// or https://",
        )),
    }
}

fn safe_relative(path: &Path) -> Result<PathBuf> {
    use std::path::Component;
    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            Component::Normal(name) => normalized.push(name),
            Component::CurDir => {}
            Component::ParentDir if normalized.pop() => {}
            _ => return Err(failure("Cached path escapes the repository")),
        }
    }
    Ok(normalized)
}

fn validate_command(argv: &[String]) -> Result<()> {
    crate::validate_command(argv)
}

fn javascript_executable(manager: &str, windows: bool) -> &str {
    match (manager, windows) {
        ("npm", true) => "npm.cmd",
        ("pnpm", true) => "pnpm.cmd",
        _ => manager,
    }
}

/// Validate repository-relative file globs. Environment and commit inputs have
/// dedicated fields so they cannot accidentally bypass the commit opt-in.
fn validate_cache_inputs(check: &Check) -> Result<()> {
    if check.cache_env.iter().any(|key| key == "CI_COMMIT_SHA") && !check.cache_commit {
        return Err(failure("CI_COMMIT_SHA requires cache_commit = true; remove it from cache_env for content-only checks"));
    }
    if let Some(inputs) = &check.cache_inputs {
        if inputs.is_empty() || !inputs.iter().any(|input| !input.starts_with('!')) {
            return Err(failure(
                "cache_inputs requires at least one positive file pattern",
            ));
        }
        for input in inputs {
            let path = input.strip_prefix('!').unwrap_or(input);
            safe_relative(Path::new(path))?;
            if path.is_empty() || path.contains(['$', '@', '\\', ':', '\0']) {
                return Err(failure(
                    "cache_inputs accepts repository-relative file patterns only",
                ));
            }
        }
    }
    Ok(())
}

/// Identity is per check: selecting a commit-sensitive build must not invalidate
/// a content-only test. Probe each distinct tool only once across the selection.
fn tool_identity(
    runner: &Runner,
    check: &Check,
    environment: &Environment,
    tool: &str,
    tool_revision: &str,
    probe_results: &mut BTreeMap<Vec<String>, String>,
) -> Result<String> {
    let mut parts = vec![
        format!("{tool} {tool_revision}"),
        format!(
            "platform {} {}",
            std::env::consts::OS,
            std::env::consts::ARCH
        ),
        format!(
            "linker {}",
            value(environment, "CI_LINKER").unwrap_or_else(|| "system".into())
        ),
        // Bind the entire declaration even when narrow globs exclude the manifest.
        serde_json::to_string(check)?,
    ];
    for key in &check.cache_env {
        if key != "CI_COMMIT_SHA" {
            parts.push(format!("env {key} {:?}", value(environment, key)));
        }
    }
    if check.cache_commit {
        let commit = value(environment, "CI_COMMIT_SHA")
            .filter(|commit| commit.len() == 40 && commit.bytes().all(|b| b.is_ascii_hexdigit()))
            .ok_or_else(|| failure("cache_commit requires an exact CI_COMMIT_SHA"))?;
        parts.push(format!("commit {commit}"));
    }
    let mut probes = check.cache_tools.clone();
    match check.kind.as_str() {
        "cargo" => match check.toolchain.as_deref().unwrap_or("system") {
            "system" => {
                probes.push(argv(&["rustc", "-vV"]));
                probes.push(argv(&["cargo", "--version"]));
            }
            toolchain => {
                probes.push(argv(&["rustup", "run", toolchain, "rustc", "-vV"]));
                probes.push(argv(&["rustup", "run", toolchain, "cargo", "--version"]));
            }
        },
        "javascript" => {
            probes.push(argv(&["node", "--version"]));
            let manager = check.manager.as_deref().unwrap_or("npm");
            probes.push(vec![
                javascript_executable(manager, cfg!(windows)).to_owned(),
                "--version".into(),
            ]);
        }
        "nix" => probes.push(argv(&["nix", "--version"])),
        _ => {}
    }
    probes.sort();
    probes.dedup();
    for probe in probes {
        if !probe_results.contains_key(&probe) {
            probe_results.insert(probe.clone(), runner.run(&probe, true)?);
        }
        parts.push(format!(
            "{}: {}",
            serde_json::to_string(&probe)?,
            probe_results[&probe]
        ));
    }
    Ok(format!("{:x}", Sha256::digest(parts.join("\n").as_bytes())))
}

fn render_workspace(project: &str) -> String {
    let mut projects = serde_json::Map::new();
    projects.insert(project.to_owned(), json!("."));
    let workspace = json!({
        "projects": projects,
        "vcs": { "client": "git" },
    });
    // YAML is a superset of JSON, so the generated JSON is valid moon YAML.
    format!(
        "{MARKER}\n{}\n",
        serde_json::to_string_pretty(&workspace).unwrap_or_default()
    )
}

fn render_tasks(
    checks: &BTreeMap<String, Check>,
    selected: &[String],
    manifest: &str,
    tool: &str,
    identities: &BTreeMap<String, String>,
) -> String {
    let mut tasks = serde_json::Map::new();
    for name in selected {
        let receipt = format!("{RESULTS}/{name}.jsonl");
        let mut outputs = checks[name].cache_outputs.clone();
        outputs.push(receipt.clone());
        let mut inputs = checks[name]
            .cache_inputs
            .clone()
            .unwrap_or_else(|| argv(&["**/*"]));
        inputs.extend(argv(&[
            "!.git/**",
            "!.moon/**",
            "!moon.yml",
            "!.ccid/**",
            "!target/**",
            "$CCID_TOOL_IDENTITY",
        ]));
        for check in checks.values() {
            for output in &check.cache_outputs {
                inputs.push(format!("!{output}"));
                inputs.push(format!("!{output}/**"));
            }
        }
        tasks.insert(
            name.clone(),
            json!({
                "command": [tool, "check", "--repo", ".", "--manifest", manifest, "--check", name],
                "env": { "CCID_RECEIPT": receipt, "CCID_TOOL_IDENTITY": identities[name] },
                "inputs": inputs,
                "outputs": outputs,
                "options": { "runFromWorkspaceRoot": true, "mutex": MUTEX }
            }),
        );
    }
    format!(
        "{MARKER}\n{}\n",
        serde_json::to_string_pretty(&json!({ "tasks": tasks })).unwrap_or_default()
    )
}

/// Write a generated file, refusing to overwrite a configuration someone else owns.
fn write_generated(path: &Path, content: &str) -> Result<()> {
    if path.exists() && !fs::read_to_string(path)?.starts_with(MARKER) {
        return Err(failure(format!(
            "{} exists and was not generated by ccid; refusing to overwrite",
            path.display()
        )));
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn task_ids_follow_moon_rules() {
        assert!(task_id("test").is_ok());
        assert!(task_id("registry-publisher").is_ok());
        assert!(task_id("a_b2").is_ok());
        assert!(task_id("").is_err());
        assert!(task_id("-lead").is_err());
        assert!(task_id("has.dot").is_err());
        assert!(task_id("sp ace").is_err());
    }

    #[test]
    fn project_ids_drop_dots() {
        assert_eq!(project_id("example.org"), "example-org");
        assert_eq!(project_id("ccid"), "ccid");
    }

    #[test]
    fn remote_cache_comes_from_environment_only() {
        let mut environment = Environment::new();
        assert_eq!(remote_cache(&environment).unwrap(), None);
        environment.insert("CCID_REMOTE_CACHE".into(), "grpc://cache:9092".into());
        assert_eq!(
            remote_cache(&environment).unwrap().as_deref(),
            Some("grpc://cache:9092")
        );
        environment.insert("CCID_REMOTE_CACHE".into(), "cache:9092".into());
        assert!(remote_cache(&environment).is_err());
    }

    #[test]
    fn workspace_is_independent_of_remote_transport() {
        let local: serde_json::Value =
            serde_json::from_str(render_workspace("demo").split_once('\n').unwrap().1).unwrap();
        assert_eq!(local["projects"]["demo"], ".");
        assert!(local.get("remote").is_none());
    }

    #[test]
    fn tasks_wrap_tool_check_with_receipt_output() {
        let checks = std::collections::BTreeMap::from([(
            "test".into(),
            Check {
                cache_outputs: vec!["binary".into()],
                ..Check::default()
            },
        )]);
        let text = render_tasks(
            &checks,
            &["test".into()],
            ".ci/ccid.toml",
            "ccid",
            &BTreeMap::from([("test".into(), "identity".into())]),
        );
        assert!(text.starts_with(MARKER));
        let tasks: serde_json::Value =
            serde_json::from_str(text.split_once('\n').unwrap().1).unwrap();
        let task = &tasks["tasks"]["test"];
        assert_eq!(
            task["command"],
            json!([
                "ccid",
                "check",
                "--repo",
                ".",
                "--manifest",
                ".ci/ccid.toml",
                "--check",
                "test"
            ])
        );
        assert_eq!(
            task["outputs"],
            json!(["binary", ".ccid/results/test.jsonl"])
        );
        assert!(task["inputs"]
            .as_array()
            .unwrap()
            .contains(&json!("!binary")));
        assert_eq!(task["options"]["mutex"], MUTEX);
        assert!(task["inputs"]
            .as_array()
            .unwrap()
            .contains(&json!("$CCID_TOOL_IDENTITY")));
    }

    fn identity(check: &Check, environment: &Environment) -> String {
        let directory = tempfile::tempdir().unwrap();
        let runner = Runner::new(
            directory.path().into(),
            environment.clone(),
            Duration::from_secs(5),
        )
        .unwrap();
        tool_identity(
            &runner,
            check,
            environment,
            "ccid",
            "revision",
            &mut BTreeMap::new(),
        )
        .unwrap()
    }

    #[test]
    fn commits_and_branches_do_not_invalidate_content_checks() {
        let check = Check {
            cache_env: vec!["GOFLAGS".into()],
            ..Check::default()
        };
        let mut environment = Environment::new();
        environment.insert("CI_COMMIT_SHA".into(), "a".repeat(40).into());
        environment.insert("CI_COMMIT_BRANCH".into(), "main".into());
        let original = identity(&check, &environment);
        environment.insert("CI_COMMIT_SHA".into(), "b".repeat(40).into());
        environment.insert("CI_COMMIT_BRANCH".into(), "other".into());
        assert_eq!(identity(&check, &environment), original);
        environment.insert("GOFLAGS".into(), "-race".into());
        assert_ne!(identity(&check, &environment), original);
    }

    #[test]
    fn commit_sensitive_check_does_not_poison_other_check_identities() {
        let content = Check::default();
        let stamp = Check {
            cache_commit: true,
            ..Check::default()
        };
        let mut environment = Environment::new();
        environment.insert("CI_COMMIT_SHA".into(), "a".repeat(40).into());
        let original = identity(&content, &environment);
        let stamped = identity(&stamp, &environment);
        environment.insert("CI_COMMIT_SHA".into(), "b".repeat(40).into());
        assert_ne!(identity(&stamp, &environment), stamped);
        assert_eq!(identity(&content, &environment), original);
        let directory = tempfile::tempdir().unwrap();
        let runner = Runner::new(
            directory.path().into(),
            Environment::new(),
            Duration::from_secs(5),
        )
        .unwrap();
        assert!(tool_identity(
            &runner,
            &stamp,
            &Environment::new(),
            "ccid",
            "revision",
            &mut BTreeMap::new()
        )
        .is_err());
    }

    #[test]
    fn tool_versions_linker_and_check_definition_remain_inputs() {
        let probe = argv(&["example-tool", "--version"]);
        let mut check = Check {
            cache_tools: vec![probe.clone()],
            ..Check::default()
        };
        let directory = tempfile::tempdir().unwrap();
        let mut environment = Environment::new();
        let runner = Runner::new(
            directory.path().into(),
            environment.clone(),
            Duration::from_secs(5),
        )
        .unwrap();
        let mut probes = BTreeMap::from([(probe.clone(), "v1".into())]);
        let original = tool_identity(
            &runner,
            &check,
            &environment,
            "ccid",
            "revision",
            &mut probes,
        )
        .unwrap();
        probes.insert(probe.clone(), "v2".into());
        assert_ne!(
            tool_identity(
                &runner,
                &check,
                &environment,
                "ccid",
                "revision",
                &mut probes
            )
            .unwrap(),
            original
        );
        probes.insert(probe, "v1".into());
        environment.insert("CI_LINKER".into(), "mold".into());
        assert_ne!(
            tool_identity(
                &runner,
                &check,
                &environment,
                "ccid",
                "revision",
                &mut probes
            )
            .unwrap(),
            original
        );
        environment.clear();
        check.commands = vec![argv(&["different-command"])];
        assert_ne!(
            tool_identity(
                &runner,
                &check,
                &environment,
                "ccid",
                "revision",
                &mut probes
            )
            .unwrap(),
            original
        );
    }

    #[test]
    fn narrow_inputs_preserve_exclusions_and_check_identity() {
        let check: Check =
            toml::from_str("cache_inputs = ['src/**', 'Cargo.*', '!src/generated/**']").unwrap();
        validate_cache_inputs(&check).unwrap();
        let checks = BTreeMap::from([("test".into(), check)]);
        let identities = BTreeMap::from([("test".into(), "identity".into())]);
        let text = render_tasks(
            &checks,
            &["test".into()],
            ".ci/ccid.toml",
            "ccid",
            &identities,
        );
        let tasks: serde_json::Value =
            serde_json::from_str(text.split_once('\n').unwrap().1).unwrap();
        let inputs = tasks["tasks"]["test"]["inputs"].as_array().unwrap();
        for required in [
            "src/**",
            "Cargo.*",
            "!src/generated/**",
            "!.git/**",
            "!.moon/**",
            "!.ccid/**",
            "!target/**",
            "$CCID_TOOL_IDENTITY",
        ] {
            assert!(inputs.contains(&json!(required)));
        }
        assert!(!inputs.contains(&json!("**/*")));
        assert_eq!(
            tasks["tasks"]["test"]["env"]["CCID_TOOL_IDENTITY"],
            "identity"
        );
        for inputs in [
            vec![],
            vec!["!docs/**"],
            vec!["../outside"],
            vec!["/absolute"],
            vec![""],
            vec!["$CI_COMMIT_SHA"],
            vec!["@group(source)"],
        ] {
            let check = Check {
                cache_inputs: Some(inputs.into_iter().map(str::to_owned).collect()),
                ..Check::default()
            };
            assert!(validate_cache_inputs(&check).is_err());
        }
        let check = Check {
            cache_env: vec!["CI_COMMIT_SHA".into()],
            ..Check::default()
        };
        assert!(validate_cache_inputs(&check).is_err());
    }

    #[test]
    fn generated_files_never_overwrite_foreign_configuration() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("moon.yml");
        fs::write(&path, "tasks: {}\n").unwrap();
        assert!(write_generated(&path, &format!("{MARKER}\n{{}}\n")).is_err());
        fs::write(&path, format!("{MARKER}\nold\n")).unwrap();
        assert!(write_generated(&path, &format!("{MARKER}\nnew\n")).is_ok());
        assert!(fs::read_to_string(&path).unwrap().ends_with("new\n"));
    }
}
