//! Result caching around selected checks through moon.
//!
//! Each selected check becomes one moon task whose command is the ordinary
//! tool check for that check. moon hashes the task's inputs, skips work whose
//! inputs already passed, and can share results through a remote cache. The
//! caller owns check semantics, budgets and receipts; moon only adds result
//! reuse. The moon configuration is generated for each run and is not
//! committed to the repository; the remote cache address comes from
//! `CCID_REMOTE_CACHE`.
use crate::{event, failure, process::Runner, value, Environment, Result};
use serde::{Deserialize, Serialize};
use serde_json::json;
use sha2::{Digest, Sha256};
use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    time::{Duration, Instant},
};

const MARKER: &str = "# ccid-generated: regenerated by `ccid cached` on every run; do not edit.";
const RESULTS: &str = ".ccid/results";
/// Every tool check locks the repository's target cache, so tasks run one at a time.
const MUTEX: &str = "ccid-target";

#[path = "shared_cache.rs"]
mod shared_cache;

struct CachePreflight {
    identity: String,
    moon_version: String,
}

/// Check declaration as owned by the caller's manifest. Field-for-field
/// compatible with ccid's manifest check: the tool identity hashes the whole
/// declaration, so this struct must serialize exactly like the caller's.
#[derive(Debug, Clone, Deserialize, Serialize, Default)]
#[serde(default, deny_unknown_fields)]
pub struct Check {
    pub kind: String,
    pub actions: Option<Vec<String>>,
    pub toolchain: Option<String>,
    pub workspace: bool,
    pub all_features: bool,
    pub all_targets: bool,
    pub release: bool,
    pub features: Vec<String>,
    pub packages: Vec<String>,
    pub exclude: Vec<String>,
    pub test_runner: Option<String>,
    pub mode: Option<String>,
    pub expected_checks: Option<Vec<String>>,
    pub checks: Vec<String>,
    pub manager: Option<String>,
    pub scripts: Option<Vec<String>>,
    pub install: Option<bool>,
    pub commands: Vec<Vec<String>>,
    pub cache_outputs: Vec<String>,
    pub cache_tools: Vec<Vec<String>>,
    pub cache_env: Vec<String>,
    pub cache_commit: bool,
    pub cache_inputs: Option<Vec<String>>,
    pub cache: Option<bool>,
    /// Explicit promise that commands/Nix do not observe moving external state
    /// or Git provenance. Required before sharing these open-ended checks.
    pub cache_pure: bool,
}

/// Validated execution request. The caller owns manifest parsing, check
/// selection and the cached-plan event; this request carries everything moon
/// needs to reproduce the run.
#[derive(Clone)]
pub struct Request {
    pub repo: PathBuf,
    pub project: String,
    pub manifest_arg: String,
    pub checks: BTreeMap<String, Check>,
    pub selected: Vec<String>,
    pub plan: bool,
    pub force: bool,
    /// Tool executable invoked per task (ccid) and hashed into identities.
    pub tool: String,
    /// Exact tool revision hashed into every task identity.
    pub tool_revision: String,
    pub environment: Environment,
}

/// Validate the selected checks before any execution: moon task names,
/// repository-relative inputs, explicit outputs and tool probes.
pub fn validate_selection(checks: &BTreeMap<String, Check>, selected: &[String]) -> Result<()> {
    for name in selected {
        let check = checks
            .get(name)
            .ok_or_else(|| failure(format!("Selected check {name} is not declared")))?;
        task_id(name)?;
        validate_cache_inputs(check)?;
        for output in &check.cache_outputs {
            safe_relative(Path::new(output))?;
            if output.starts_with('.') || output.contains(['*', '?', '[', ']']) {
                return Err(failure(
                    "Cached outputs must be explicit, non-hidden relative paths",
                ));
            }
        }
        for command in &check.cache_tools {
            validate_command(command)?;
        }
    }
    Ok(())
}

/// Run the selected checks through moon so unchanged inputs reuse earlier results.
pub fn execute(request: &Request) -> Result<()> {
    for name in &request.selected {
        if !request.checks.contains_key(name) {
            return Err(failure(format!("Selected check {name} is not declared")));
        }
    }
    if request.plan {
        return Ok(());
    }
    let timeout = value(&request.environment, "CI_TIMEOUT")
        .and_then(|s| s.parse().ok())
        .unwrap_or(2700);
    let deadline = Instant::now()
        .checked_add(Duration::from_secs(timeout))
        .ok_or_else(|| failure("Cache deadline overflow"))?;
    let mut measurements = Vec::new();
    let mut bypassed = Vec::new();
    for name in &request.selected {
        let mut one = request.clone();
        one.selected = vec![name.clone()];
        let remaining = deadline.saturating_duration_since(Instant::now());
        if remaining.is_zero() {
            return Err(failure("Check deadline exceeded"));
        }
        one.environment.insert(
            "CI_TIMEOUT".into(),
            remaining.as_secs().max(1).to_string().into(),
        );
        let mut prepared = None;
        let reason = cache_bypass_reason(&one, &mut prepared);
        let remaining = deadline.saturating_duration_since(Instant::now());
        if remaining.is_zero() {
            return Err(failure("Check deadline exceeded"));
        }
        one.environment.insert(
            "CI_TIMEOUT".into(),
            remaining.as_secs().max(1).to_string().into(),
        );
        let mut reason = reason;
        if reason.is_none() {
            let preflight = prepared
                .take()
                .ok_or_else(|| failure("Missing cache preflight"))?;
            match shared_cache::execute(&one, preflight) {
                Ok(()) => {
                    let metrics: serde_json::Value = serde_json::from_slice(&fs::read(
                        one.repo.join(".ccid/cache-metrics.json"),
                    )?)?;
                    measurements.extend(
                        metrics["checks"]
                            .as_array()
                            .ok_or_else(|| failure("Missing cache measurements"))?
                            .iter()
                            .cloned(),
                    );
                    continue;
                }
                // The ledger refused before any compute started: degrade to an
                // ordinary uncached check instead of failing the job.
                Err(error) => {
                    if error
                        .downcast_ref::<crate::content_key::LedgerRefusal>()
                        .is_none()
                    {
                        return Err(error);
                    }
                    reason = Some(format!("result ledger unavailable for this key: {error}"));
                }
            }
        }
        if let Some(reason) = reason {
            event(
                json!({"event":"cache-bypass","check":name,"reason":reason,"execution":"uncached"}),
            );
            // Preserve the ordinary check environment and product exit status.
            // Never retry here after a cache transaction has begun executing.
            let mut env = one.environment.clone();
            for key in [
                "CCID_RESULT_CACHE",
                "CCID_CACHE_CHILD",
                "CCID_CACHE_REPLAY_ONLY",
                "CCID_TOOL_IDENTITY",
            ] {
                env.remove(std::ffi::OsStr::new(key));
            }
            let receipt_relative = format!("{RESULTS}/{name}.jsonl");
            safe_relative(Path::new(&receipt_relative))?;
            let receipt = one.repo.join(receipt_relative);
            fs::create_dir_all(
                receipt
                    .parent()
                    .ok_or_else(|| failure("Missing receipt directory"))?,
            )?;
            fs::write(
                &receipt,
                format!(
                    "{}\n",
                    json!({"event":"cache-bypass","check":name,"reason":reason,"execution":"uncached"})
                ),
            )?;
            env.insert("CCID_RECEIPT".into(), receipt.into_os_string());
            let mut command = vec![
                one.tool.clone(),
                "check".into(),
                "--repo".into(),
                ".".into(),
                "--manifest".into(),
                one.manifest_arg.clone(),
                "--check".into(),
                name.clone(),
            ];
            // Timing is optional instrumentation, never a check prerequisite.
            let timer = value(&env, "CMNP_TIME")
                .filter(|path| Path::new(path).is_file())
                .and_then(|time| {
                    tempfile::NamedTempFile::new_in(one.repo.join(".ccid"))
                        .ok()
                        .map(|file| (time, file))
                });
            if let Some((time, file)) = &timer {
                let mut measured = vec![
                    time.clone(),
                    "-q".into(),
                    "-f".into(),
                    "{\"user\":%U,\"system\":%S}".into(),
                    "-o".into(),
                    file.path().to_string_lossy().into_owned(),
                    "--".into(),
                ];
                measured.extend(command);
                command = measured;
            }
            let outcome = Runner::new(one.repo.clone(), env, remaining)?.run(&command, false);
            let cpu: Option<serde_json::Value> = timer.and_then(|(_, file)| {
                fs::read(file.path())
                    .ok()
                    .and_then(|bytes| serde_json::from_slice(&bytes).ok())
            });
            let measurement = json!({"event":"cache-bypass-complete","check":name,"reason":reason,"cpu_seconds":cpu,"success":outcome.is_ok()});
            event(measurement.clone());
            bypassed.push(measurement);
            outcome?;
        }
    }
    let hits = measurements.iter().filter(|r| r["computed"] == 0).count();
    let requests = measurements.len();
    let summary = json!({"event":"cache-run","checks":measurements,"bypassed":bypassed,
        "result":{"hits":hits,"requests":requests,"hit_rate":if requests == 0 { None } else { Some(hits as f64 / requests as f64) }},
        "compile":null,"nix_eval":null,"fetch":null});
    fs::create_dir_all(request.repo.join(".ccid"))?;
    fs::write(
        request.repo.join(".ccid/cache-metrics.json"),
        serde_json::to_vec_pretty(&summary)?,
    )?;
    event(summary);
    Ok(())
}

fn supported_moon(version: &str) -> bool {
    version.trim() == "moon 2.4.6" || version.starts_with("moon 2.5.")
}

/// Cache availability is a preflight decision, never a reason to skip product
/// checks or to replay an already-started computation after an error.
fn cache_bypass_reason(request: &Request, prepared: &mut Option<CachePreflight>) -> Option<String> {
    if request.force {
        return Some("uncached execution explicitly requested".into());
    }
    let check = &request.checks[&request.selected[0]];
    if check.cache == Some(false) || check.cache_commit {
        return Some("check is explicitly not result-cacheable".into());
    }
    if matches!(check.kind.as_str(), "commands" | "nix") && !check.cache_pure {
        return Some("no explicit pure-result contract".into());
    }
    if check.kind == "commands" && (check.cache_inputs.is_none() || check.cache_tools.is_empty()) {
        return Some("no complete input and tool contract".into());
    }
    if let Err(error) = validate_selection(&request.checks, &request.selected) {
        return Some(format!("result-cache contract is unavailable: {error}"));
    }
    let Some(root) = value(&request.environment, "CCID_RESULT_CACHE") else {
        return Some("CCID_RESULT_CACHE is not provisioned".into());
    };
    if let Err(error) = crate::content_key::validate_root(Path::new(&root)) {
        return Some(format!("result-cache storage unavailable: {error}"));
    }
    if let Err(error) = tempfile::NamedTempFile::new_in(&root) {
        return Some(format!("result-cache storage is not writable: {error}"));
    }
    let runner = match Runner::new(
        request.repo.clone(),
        request.environment.clone(),
        Duration::from_secs(30),
    ) {
        Ok(runner) => runner,
        Err(error) => return Some(format!("cache preflight unavailable: {error}")),
    };
    if check.kind == "nix" {
        let clean = request.repo.join(".git").exists()
            && runner
                .run(
                    &argv(&["git", "status", "--porcelain", "--untracked-files=no"]),
                    true,
                )
                .is_ok_and(|status| status.is_empty());
        if !clean {
            return Some("Nix result cache requires a committed clean flake".into());
        }
    }
    if let Err(error) = crate::inputs::lock_digest(&request.repo, check) {
        return Some(format!("dependency lock is not cacheable: {error}"));
    }
    let identity = match tool_identity(
        &runner,
        check,
        &request.environment,
        &request.tool,
        &request.tool_revision,
        &mut BTreeMap::new(),
    ) {
        Ok(identity) => identity,
        Err(error) => return Some(format!("tool identity is not cacheable: {error}")),
    };
    match runner.run(&argv(&["moon", "--version"]), true) {
        Ok(version) if supported_moon(&version) => {
            *prepared = Some(CachePreflight {
                identity,
                moon_version: version,
            });
            None
        }
        Ok(version) => Some(format!("unsupported result-cache runtime: {version}")),
        Err(_) => Some("moon is unavailable; running ordinary checks".into()),
    }
}

fn argv(args: &[&str]) -> Vec<String> {
    args.iter().map(|s| (*s).to_owned()).collect()
}

/// moon task identifiers: letters, digits, dash and underscore.
fn task_id(name: &str) -> Result<()> {
    let valid = name
        .bytes()
        .next()
        .is_some_and(|b| b.is_ascii_alphanumeric())
        && name
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_');
    if valid {
        Ok(())
    } else {
        Err(failure(format!(
            "Check name {name:?} is not usable as a cached task; use letters, digits, '-' or '_'"
        )))
    }
}

/// moon project identifiers do not allow dots; manifest slugs may contain them.
pub fn project_id(slug: &str) -> String {
    slug.replace('.', "-")
}

/// The remote cache endpoint, from the runner environment (never from the repository).
pub fn remote_cache(environment: &Environment) -> Result<Option<String>> {
    match value(environment, "CCID_REMOTE_CACHE") {
        None => Ok(None),
        Some(url)
            if ["grpc://", "grpcs://", "http://", "https://"]
                .iter()
                .any(|scheme| url.starts_with(scheme)) =>
        {
            Ok(Some(url))
        }
        Some(_) => Err(failure(
            "CCID_REMOTE_CACHE must start with grpc://, grpcs://, http:// or https://",
        )),
    }
}

fn safe_relative(path: &Path) -> Result<PathBuf> {
    use std::path::Component;
    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            Component::Normal(name) => normalized.push(name),
            Component::CurDir => {}
            Component::ParentDir if normalized.pop() => {}
            _ => return Err(failure("Cached path escapes the repository")),
        }
    }
    Ok(normalized)
}

fn validate_command(argv: &[String]) -> Result<()> {
    crate::validate_command(argv)
}

fn javascript_executable(manager: &str, windows: bool) -> &str {
    match (manager, windows) {
        ("npm", true) => "npm.cmd",
        ("pnpm", true) => "pnpm.cmd",
        _ => manager,
    }
}

/// Validate repository-relative file globs. Environment and commit inputs have
/// dedicated fields so they cannot accidentally bypass the commit opt-in.
fn validate_cache_inputs(check: &Check) -> Result<()> {
    if check.cache_env.iter().any(|key| {
        ["CI_COMMIT_", "CI_JOB_", "CI_PIPELINE_", "CI_RUN_", "MOON_"]
            .iter()
            .any(|prefix| key.starts_with(prefix))
            || ["RUNNER_TEMP", "TMPDIR", "TEMP", "TMP"].contains(&key.as_str())
    }) {
        return Err(failure(
            "Run metadata and temporary paths cannot be cache environment inputs",
        ));
    }
    if check.kind == "javascript" && check.install == Some(false) {
        return Err(failure("Cached JavaScript requires a locked install; ambient node_modules is not an input contract"));
    }
    if check.cache_env.iter().any(|key| key == "CI_COMMIT_SHA") && !check.cache_commit {
        return Err(failure("CI_COMMIT_SHA requires cache_commit = true; remove it from cache_env for content-only checks"));
    }
    if let Some(inputs) = &check.cache_inputs {
        if inputs.is_empty() || !inputs.iter().any(|input| !input.starts_with('!')) {
            return Err(failure(
                "cache_inputs requires at least one positive file pattern",
            ));
        }
        for input in inputs {
            let path = input.strip_prefix('!').unwrap_or(input);
            safe_relative(Path::new(path))?;
            if path.is_empty() || path.contains(['$', '@', '\\', ':', '\0']) {
                return Err(failure(
                    "cache_inputs accepts repository-relative file patterns only",
                ));
            }
        }
    }
    Ok(())
}

/// Identity is per check: selecting a commit-sensitive build must not invalidate
/// a content-only test. Probe each distinct tool only once across the selection.
fn tool_identity(
    runner: &Runner,
    check: &Check,
    environment: &Environment,
    tool: &str,
    _tool_revision: &str,
    probe_results: &mut BTreeMap<Vec<String>, String>,
) -> Result<String> {
    let mut tools = BTreeMap::from([("executor".to_owned(), tool.to_owned())]);
    let mut parts = vec![
        format!(
            "platform {} {}",
            std::env::consts::OS,
            std::env::consts::ARCH
        ),
        format!(
            "linker {}",
            value(environment, "CI_LINKER").unwrap_or_else(|| "system".into())
        ),
        // Bind the entire declaration even when narrow globs exclude the manifest.
        serde_json::to_string(check)?,
    ];
    parts.push(serde_json::to_string(
        &crate::inputs::semantic_environment(check, environment),
    )?);
    if check.cache_commit {
        return Err(failure(
            "Commit-sensitive checks cannot share content results",
        ));
    }
    let mut probes = check.cache_tools.clone();
    match check.kind.as_str() {
        "cargo" => match check.toolchain.as_deref().unwrap_or("system") {
            "system" => {
                probes.push(argv(&["rustc", "-vV"]));
                probes.push(argv(&["cargo", "--version"]));
            }
            toolchain => {
                probes.push(argv(&["rustup", "run", toolchain, "rustc", "-vV"]));
                probes.push(argv(&["rustup", "run", toolchain, "cargo", "--version"]));
            }
        },
        "javascript" => {
            let manager = check.manager.as_deref().unwrap_or("npm");
            if manager != "deno" {
                probes.push(argv(&["node", "--version"]));
            }
            probes.push(vec![
                javascript_executable(manager, cfg!(windows)).to_owned(),
                "--version".into(),
            ]);
        }
        "nix" => probes.push(argv(&["nix", "--version"])),
        _ => {}
    }
    probes.sort();
    probes.dedup();
    for probe in probes {
        if !probe_results.contains_key(&probe) {
            probe_results.insert(probe.clone(), runner.run(&probe, true)?);
        }
        parts.push(format!(
            "{}: {}",
            serde_json::to_string(&probe)?,
            probe_results[&probe]
        ));
        tools.insert(format!("probe:{}", probe[0]), probe[0].clone());
    }
    if check.kind == "cargo" {
        let sysroot = match check.toolchain.as_deref().unwrap_or("system") {
            "system" => runner.run(&argv(&["rustc", "--print", "sysroot"]), true)?,
            toolchain => runner.run(
                &argv(&["rustup", "run", toolchain, "rustc", "--print", "sysroot"]),
                true,
            )?,
        };
        let sysroot = Path::new(&sysroot).canonicalize()?;
        if !sysroot.starts_with("/nix/store") {
            return Err(failure("Cached Cargo currently requires an immutable Nix compiler sysroot; use an uncached check for mutable toolchains"));
        }
        tools.insert(
            "compiler-runtime".into(),
            sysroot.join("bin/rustc").to_string_lossy().into_owned(),
        );
        if check.test_runner.as_deref() == Some("nextest") {
            tools.insert("test-runner".into(), "cargo-nextest".into());
        }
        for (role, variable) in [("c-compiler", "CC"), ("cxx-compiler", "CXX")] {
            if let Some(name) = value(environment, variable) {
                tools.insert(role.into(), name);
            }
        }
        if value(environment, "CI_LINKER").as_deref() == Some("mold") {
            tools.insert("linker".into(), "mold".into());
        }
        for name in ["cc", "cargo-clippy", "rustfmt"] {
            if crate::inputs::executable(name, environment).is_ok() {
                tools.insert(name.into(), name.into());
            }
        }
        if let Some(wrapper) = value(environment, "RUSTC_WRAPPER").filter(|s| !s.is_empty()) {
            tools.insert("wrapper".into(), wrapper);
        }
    }
    parts.push(crate::inputs::tool_set_digest(&tools, runner)?);
    Ok(format!("{:x}", Sha256::digest(parts.join("\n").as_bytes())))
}

fn render_workspace(project: &str) -> String {
    let mut projects = serde_json::Map::new();
    projects.insert(project.to_owned(), json!("."));
    let workspace = json!({
        "projects": projects,
        "vcs": { "client": "git" },
    });
    // YAML is a superset of JSON, so the generated JSON is valid moon YAML.
    format!(
        "{MARKER}\n{}\n",
        serde_json::to_string_pretty(&workspace).unwrap_or_default()
    )
}

fn render_tasks(
    checks: &BTreeMap<String, Check>,
    selected: &[String],
    manifest: &str,
    tool: &str,
    identities: &BTreeMap<String, String>,
) -> String {
    let mut tasks = serde_json::Map::new();
    for name in selected {
        let receipt = format!("{RESULTS}/{name}.jsonl");
        let mut outputs = checks[name].cache_outputs.clone();
        outputs.push(receipt.clone());
        // The central snapshot already binds files, locks, flags, tools and
        // semantic environment. Native hashing must not reintroduce job paths.
        let inputs = argv(&["$CCID_TOOL_IDENTITY"]);
        tasks.insert(
            name.clone(),
            json!({
                "command": [tool, "check", "--repo", ".", "--manifest", manifest, "--check", name],
                "env": { "CCID_RECEIPT": receipt, "CCID_TOOL_IDENTITY": identities[name], "CCID_CACHE_CHILD": "1" },
                "inputs": inputs,
                "outputs": outputs,
                "options": { "runFromWorkspaceRoot": true, "mutex": MUTEX }
            }),
        );
    }
    format!(
        "{MARKER}\n{}\n",
        serde_json::to_string_pretty(&json!({ "tasks": tasks })).unwrap_or_default()
    )
}

/// Write a generated file, refusing to overwrite a configuration someone else owns.
fn write_generated(path: &Path, content: &str) -> Result<()> {
    if path.exists() && !fs::read_to_string(path)?.starts_with(MARKER) {
        return Err(failure(format!(
            "{} exists and was not generated by ccid; refusing to overwrite",
            path.display()
        )));
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn current_and_legacy_moon_versions_are_supported() {
        assert!(supported_moon("moon 2.4.6"));
        assert!(supported_moon("moon 2.5.4"));
        assert!(!supported_moon("moon 2.4.5"));
        assert!(!supported_moon("moon 3.0.0"));
    }

    #[test]
    fn task_ids_follow_moon_rules() {
        assert!(task_id("test").is_ok());
        assert!(task_id("registry-publisher").is_ok());
        assert!(task_id("a_b2").is_ok());
        assert!(task_id("").is_err());
        assert!(task_id("-lead").is_err());
        assert!(task_id("has.dot").is_err());
        assert!(task_id("sp ace").is_err());
    }

    #[test]
    fn project_ids_drop_dots() {
        assert_eq!(project_id("example.org"), "example-org");
        assert_eq!(project_id("ccid"), "ccid");
    }

    #[test]
    fn remote_cache_comes_from_environment_only() {
        let mut environment = Environment::new();
        assert_eq!(remote_cache(&environment).unwrap(), None);
        environment.insert("CCID_REMOTE_CACHE".into(), "grpc://cache:9092".into());
        assert_eq!(
            remote_cache(&environment).unwrap().as_deref(),
            Some("grpc://cache:9092")
        );
        environment.insert("CCID_REMOTE_CACHE".into(), "cache:9092".into());
        assert!(remote_cache(&environment).is_err());
    }

    #[test]
    fn workspace_is_independent_of_remote_transport() {
        let local: serde_json::Value =
            serde_json::from_str(render_workspace("demo").split_once('\n').unwrap().1).unwrap();
        assert_eq!(local["projects"]["demo"], ".");
        assert!(local.get("remote").is_none());
    }

    #[test]
    fn tasks_wrap_tool_check_with_receipt_output() {
        let checks = std::collections::BTreeMap::from([(
            "test".into(),
            Check {
                cache_outputs: vec!["binary".into()],
                ..Check::default()
            },
        )]);
        let text = render_tasks(
            &checks,
            &["test".into()],
            ".ci/ccid.toml",
            "ccid",
            &BTreeMap::from([("test".into(), "identity".into())]),
        );
        assert!(text.starts_with(MARKER));
        let tasks: serde_json::Value =
            serde_json::from_str(text.split_once('\n').unwrap().1).unwrap();
        let task = &tasks["tasks"]["test"];
        assert_eq!(
            task["command"],
            json!([
                "ccid",
                "check",
                "--repo",
                ".",
                "--manifest",
                ".ci/ccid.toml",
                "--check",
                "test"
            ])
        );
        assert_eq!(
            task["outputs"],
            json!(["binary", ".ccid/results/test.jsonl"])
        );
        assert_eq!(task["inputs"], json!(["$CCID_TOOL_IDENTITY"]));
        assert_eq!(task["options"]["mutex"], MUTEX);
        assert!(task["inputs"]
            .as_array()
            .unwrap()
            .contains(&json!("$CCID_TOOL_IDENTITY")));
    }

    fn identity(check: &Check, environment: &Environment) -> String {
        let directory = tempfile::tempdir().unwrap();
        let runner = Runner::new(
            directory.path().into(),
            environment.clone(),
            Duration::from_secs(5),
        )
        .unwrap();
        tool_identity(
            &runner,
            check,
            environment,
            std::env::current_exe().unwrap().to_str().unwrap(),
            "revision",
            &mut BTreeMap::new(),
        )
        .unwrap()
    }

    #[test]
    fn commits_and_branches_do_not_invalidate_content_checks() {
        let check = Check {
            cache_env: vec!["GOFLAGS".into()],
            ..Check::default()
        };
        let mut environment = Environment::new();
        environment.insert("CI_COMMIT_SHA".into(), "a".repeat(40).into());
        environment.insert("CI_COMMIT_BRANCH".into(), "main".into());
        let original = identity(&check, &environment);
        environment.insert("CI_COMMIT_SHA".into(), "b".repeat(40).into());
        environment.insert("CI_COMMIT_BRANCH".into(), "other".into());
        assert_eq!(identity(&check, &environment), original);
        environment.insert("GOFLAGS".into(), "-race".into());
        assert_ne!(identity(&check, &environment), original);
    }

    #[test]
    fn commit_sensitive_check_does_not_poison_other_check_identities() {
        let content = Check::default();
        let stamp = Check {
            cache_commit: true,
            ..Check::default()
        };
        let mut environment = Environment::new();
        environment.insert("CI_COMMIT_SHA".into(), "a".repeat(40).into());
        let original = identity(&content, &environment);
        environment.insert("CI_COMMIT_SHA".into(), "b".repeat(40).into());
        assert_eq!(identity(&content, &environment), original);
        let directory = tempfile::tempdir().unwrap();
        let runner = Runner::new(
            directory.path().into(),
            Environment::new(),
            Duration::from_secs(5),
        )
        .unwrap();
        assert!(tool_identity(
            &runner,
            &stamp,
            &Environment::new(),
            std::env::current_exe().unwrap().to_str().unwrap(),
            "revision",
            &mut BTreeMap::new()
        )
        .is_err());
    }

    #[test]
    fn tool_versions_linker_and_check_definition_remain_inputs() {
        let tool = std::env::current_exe()
            .unwrap()
            .to_string_lossy()
            .into_owned();
        let probe = argv(&[&tool, "--version"]);
        let mut check = Check {
            cache_tools: vec![probe.clone()],
            ..Check::default()
        };
        let directory = tempfile::tempdir().unwrap();
        let mut environment = Environment::new();
        let runner = Runner::new(
            directory.path().into(),
            environment.clone(),
            Duration::from_secs(5),
        )
        .unwrap();
        let mut probes = BTreeMap::from([(probe.clone(), "v1".into())]);
        let original = tool_identity(
            &runner,
            &check,
            &environment,
            &tool,
            "revision",
            &mut probes,
        )
        .unwrap();
        probes.insert(probe.clone(), "v2".into());
        assert_ne!(
            tool_identity(
                &runner,
                &check,
                &environment,
                &tool,
                "revision",
                &mut probes
            )
            .unwrap(),
            original
        );
        probes.insert(probe, "v1".into());
        environment.insert("CI_LINKER".into(), "mold".into());
        assert_ne!(
            tool_identity(
                &runner,
                &check,
                &environment,
                &tool,
                "revision",
                &mut probes
            )
            .unwrap(),
            original
        );
        environment.clear();
        check.commands = vec![argv(&["different-command"])];
        assert_ne!(
            tool_identity(
                &runner,
                &check,
                &environment,
                &tool,
                "revision",
                &mut probes
            )
            .unwrap(),
            original
        );
    }

    #[test]
    fn narrow_inputs_preserve_exclusions_and_check_identity() {
        let check: Check =
            toml::from_str("cache_inputs = ['src/**', 'Cargo.*', '!src/generated/**']").unwrap();
        validate_cache_inputs(&check).unwrap();
        let checks = BTreeMap::from([("test".into(), check)]);
        let identities = BTreeMap::from([("test".into(), "identity".into())]);
        let text = render_tasks(
            &checks,
            &["test".into()],
            ".ci/ccid.toml",
            "ccid",
            &identities,
        );
        let tasks: serde_json::Value =
            serde_json::from_str(text.split_once('\n').unwrap().1).unwrap();
        let inputs = tasks["tasks"]["test"]["inputs"].as_array().unwrap();
        assert_eq!(inputs, &vec![json!("$CCID_TOOL_IDENTITY")]);
        assert_eq!(
            tasks["tasks"]["test"]["env"]["CCID_TOOL_IDENTITY"],
            "identity"
        );
        for inputs in [
            vec![],
            vec!["!docs/**"],
            vec!["../outside"],
            vec!["/absolute"],
            vec![""],
            vec!["$CI_COMMIT_SHA"],
            vec!["@group(source)"],
        ] {
            let check = Check {
                cache_inputs: Some(inputs.into_iter().map(str::to_owned).collect()),
                ..Check::default()
            };
            assert!(validate_cache_inputs(&check).is_err());
        }
        let check = Check {
            cache_env: vec!["CI_COMMIT_SHA".into()],
            ..Check::default()
        };
        assert!(validate_cache_inputs(&check).is_err());
    }

    #[test]
    fn generated_files_never_overwrite_foreign_configuration() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("moon.yml");
        fs::write(&path, "tasks: {}\n").unwrap();
        assert!(write_generated(&path, &format!("{MARKER}\n{{}}\n")).is_err());
        fs::write(&path, format!("{MARKER}\nold\n")).unwrap();
        assert!(write_generated(&path, &format!("{MARKER}\nnew\n")).is_ok());
        assert!(fs::read_to_string(&path).unwrap().ends_with("new\n"));
    }
}
